name: flutter_writers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

  writer:
    path: modules/features/writer/
  uikit:
    path: modules/libraries/uikit/  

dev_dependencies: 
  dart_code_metrics: ^4.9.1    
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
  - modules/features/writer/assets/writers/
