name: flutter_writers
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1

  writer:
    path: modules/features/writer/

flutter:
  uses-material-design: true
  assets:
  - modules/features/writer/assets/writers/
