name: uikit
version: 1.0.0+1
publish_to: 'none'

environment: 
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies: 
  flutter:
    sdk: flutter

dev_dependencies: 
  dart_code_metrics: ^4.9.1    
  flutter_lints: ^1.0.4    

flutter: 
  uses-material-design: true  
