name: writer
version: 1.0.0+1
publish_to: 'none'

environment: 
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies: 
  flutter:
    sdk: flutter
  get: ^4.6.1 

flutter: 
  uses-material-design: true  
